const http = require('http');



const server = http.createServer((require, response) => {
    response.writeHead(200, {'content-type': 'text/html'});
    response.end('<p>hello world </p>')
})

server.listen(3000, () => {
    console.log('listen at 3000 port');
})



let process =  {
    title: 'node',
    version: 'v8.10.0',
    versions: 
     { http_parser: '2.7.0',
       node: '8.10.0',
       v8: '6.2.414.50',
       uv: '1.19.1',
       zlib: '1.2.11',
       ares: '1.10.1-DEV',
       modules: '57',
       nghttp2: '1.25.0',
       openssl: '1.0.2n',
       icu: '60.1',
       unicode: '10.0',
       cldr: '32.0',
       tz: '2017c' },
    arch: 'x64',
    platform: 'darwin',
    release: 
     { name: 'node',
       lts: 'Carbon',
       sourceUrl: 'https://nodejs.org/download/release/v8.10.0/node-v8.10.0.tar.gz',
       headersUrl: 'https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz' },
    argv: 
     [ '/usr/local/bin/node',
       '/Users/liqiankun/VSCodeProject/nodelearn/blog_express/bin/www',
       './bin/www.js' ],
    execArgv: [],
    env: 
     { npm_config_dry_run: '',
       npm_config_legacy_bundling: '',
       npm_config_save_dev: '',
       npm_config_browser: '',
       npm_config_commit_hooks: 'true',
       npm_config_only: '',
       npm_config_viewer: 'man',
       npm_config_also: '',
       TERM_PROGRAM: 'vscode',
       npm_config_rollback: 'true',
       npm_config_sign_git_commit: '',
       npm_config_audit: 'true',
       npm_config_usage: '',
       NODE: '/usr/local/bin/node',
       M2: '/Users/liqiankun/apache-maven-3.5.2/bin',
       ANDROID_HOME: '/Users/liqiankun/Library/android-sdk-macosx',
       INIT_CWD: '/Users/liqiankun/VSCodeProject/nodelearn/blog_express',
       TERM: 'xterm-256color',
       SHELL: '/bin/bash',
       npm_config___registry_npmjs_org__email: '1291878553@qq.com',
       npm_config___registry_npmjs_org__always_auth: '',
       npm_config_globalignorefile: '/usr/local/etc/npmignore',
       npm_package_dependencies_serve_favicon: '~2.4.2',
       npm_config_init_author_url: '',
       npm_config_maxsockets: '50',
       npm_config_shell: '/bin/bash',
       TMPDIR: '/var/folders/k3/jljp0nzx523b73jhk6cldtqr0000gn/T/',
       npm_config_metrics_registry: 'https://registry.npm.taobao.org/',
       npm_config_parseable: '',
       npm_config_shrinkwrap: 'true',
       Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.BjG3lJxysJ/Render',
       npm_config_init_license: 'ISC',
       npm_config_timing: '',
       TERM_PROGRAM_VERSION: '1.45.0',
       npm_package_dependencies_crypto: '^1.0.1',
       npm_package_dependencies_debug: '~2.6.3',
       npm_config_if_present: '',
       npm_package_scripts_dev: 'cross-env NODE_ENV=dev port=8000 nodemon ./bin/www.js',
       npm_config_cache_max: 'Infinity',
       npm_config_init_author_email: '',
       npm_config_sign_git_tag: '',
       npm_package_dependencies_mysql: '^2.18.1',
       npm_config_cert: '',
       npm_config_git_tag_version: 'true',
       npm_config_local_address: '',
       npm_config_long: '',
       npm_config_preid: '',
       npm_package_private: 'true',
       npm_config_registry: 'https://registry.npm.taobao.org/',
       npm_config_fetch_retries: '2',
       npm_config_noproxy: '',
       npm_config_key: '',
       npm_config_message: '%s',
       npm_config_versions: '',
       USER: 'liqiankun',
       CLASS_PATH: '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib:',
       COMMAND_MODE: 'unix2003',
       npm_config_globalconfig: '/usr/local/etc/npmrc',
       npm_config_always_auth: '',
       npm_config_logs_max: '10',
       npm_config_prefer_online: '',
       SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.5VZMy00orx/Listeners',
       PUB_HOSTED_URL: 'https://pub.flutter-io.cn',
       HOMEBREW_NO_AUTO_UPDATE: 'true',
       __CF_USER_TEXT_ENCODING: '0x1F5:0x19:0x34',
       npm_config_cache_lock_retries: '10',
       npm_config_global_style: '',
       npm_execpath: '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
       npm_config_cafile: '',
       npm_config_update_notifier: 'true',
       npm_config_audit_level: 'low',
       npm_config_heading: 'npm',
       npm_config_fetch_retry_mintimeout: '10000',
       npm_config_offline: '',
       npm_config_read_only: '',
       npm_config_searchlimit: '20',
       MAVEN_HOME: '/Users/liqiankun/Downloads/apache-maven-3.0.5',
       PATH: '/Users/liqiankun/VSCodeProject/nodelearn/blog_express/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/liqiankun/VSCodeProject/nodelearn/blog_express/node_modules/.bin:/Users/liqiankun/Downloads/flutter/bin:/Users/liqiankun/apache-maven-3.5.2/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/liqiankun/Downloads/flutter/bin:/Users/liqiankun/apache-maven-3.5.2/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/usr/local/nginx/sbin:/usr/local/sbin:/Users/liqiankun/Library/android-sdk-macosx/tools:/Users/liqiankun/Library/android-sdk-macosx/platform-tools:/Users/liqiankun/Downloads/apache-maven-3.0.5/bin:/Users/liqiankun/Downloads/apache-tomcat-7.0.85/bin:/usr/local/mongodb/bin:/usr/local/mysql/bim:/usr/local/mysql/support-files:/usr/local/sbin:/Users/liqiankun/Library/android-sdk-macosx/tools:/Users/liqiankun/Library/android-sdk-macosx/platform-tools:/Users/liqiankun/Downloads/apache-maven-3.0.5/bin:/Users/liqiankun/Downloads/apache-tomcat-7.0.85/bin:/Users/liqiankun/Library/android-sdk-macosx/tools:/Users/liqiankun/Library/android-sdk-macosx/platform-tools:/usr/local/mongodb/bin:/usr/local/mysql/bim:/usr/local/mysql/support-files',
       npm_config_argv: '{"remain":[],"cooked":["run","dev"],"original":["run","dev"]}',
       npm_config_access: '',
       npm_config_json: '',
       NGINX_HOME: '/usr/local/nginx',
       npm_config_allow_same_version: '',
       _: '/usr/local/bin/node',
       npm_config_https_proxy: '',
       npm_config_description: 'true',
       npm_config_engine_strict: '',
       npm_config_init_module: '/Users/liqiankun/.npm-init.js',
       npm_config_userconfig: '/Users/liqiankun/.npmrc',
       PWD: '/Users/liqiankun/VSCodeProject/nodelearn/blog_express',
       npm_config_cidr: '',
       JAVA_HOME: '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home',
       FLUTTER_STORAGE_BASE_URL: 'https://storage.flutter-io.cn',
       npm_config_node_version: '8.10.0',
       npm_config_user: '',
       npm_lifecycle_event: 'dev',
       LANG: 'zh_CN.UTF-8',
       npm_package_name: 'blog-express',
       npm_config_auth_type: 'legacy',
       npm_config_editor: 'vi',
       npm_config_ignore_prepublish: '',
       npm_config_save: 'true',
       npm_package_dependencies_body_parser: '~1.17.1',
       npm_config_script_shell: '',
       npm_config_tag: 'latest',
       npm_package_scripts_start: 'node ./bin/www',
       npm_config___registry_npmjs_org__username: 'liqiankun',
       npm_config_before: '',
       npm_config_global: '',
       npm_config_progress: 'true',
       XPC_FLAGS: '0x0',
       npm_config_ham_it_up: '',
       npm_config_optional: 'true',
       npm_config_searchstaleness: '900',
       NODE_ENV: 'dev',
       npm_config_bin_links: 'true',
       npm_config_force: '',
       npm_config_save_prod: '',
       npm_config_searchopts: '',
       npm_package_dependencies_express_session: '^1.17.1',
       npm_config_depth: 'Infinity',
       npm_config_node_gyp: '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
       XPC_SERVICE_NAME: '0',
       npm_package_version: '0.0.0',
       npm_config_rebuild_bundle: 'true',
       npm_config_sso_poll_frequency: '500',
       npm_config_unicode: 'true',
       SHLVL: '4',
       M2_HOME: '/Users/liqiankun/apache-maven-3.5.2',
       HOME: '/Users/liqiankun',
       VSCODE_GIT_ASKPASS_MAIN: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js',
       npm_config_fetch_retry_maxtimeout: '60000',
       npm_package_dependencies_cookie_parser: '~1.4.3',
       npm_package_dependencies_jade: '~1.11.0',
       npm_config_ca: '',
       npm_config_loglevel: 'notice',
       npm_config_save_prefix: '^',
       npm_config_scripts_prepend_node_path: 'warn-only',
       npm_config_sso_type: 'oauth',
       npm_config_strict_ssl: 'true',
       npm_config_tag_version_prefix: 'v',
       npm_package_devDependencies_cross_env: '^7.0.2',
       npm_config_dev: '',
       npm_config_fetch_retry_factor: '10',
       npm_config_group: '20',
       npm_config_save_exact: '',
       npm_package_dependencies_morgan: '~1.8.1',
       npm_package_dependencies_xss: '^1.0.6',
       npm_config_cache_lock_stale: '60000',
       npm_config_prefer_offline: '',
       npm_config_version: '',
       npm_config_cache_min: '10',
       npm_config_otp: '',
       LOGNAME: 'liqiankun',
       npm_config_cache: '/Users/liqiankun/.npm',
       npm_config_searchexclude: '',
       npm_config_color: 'true',
       npm_lifecycle_script: 'cross-env NODE_ENV=dev port=8000 nodemon ./bin/www.js',
       VSCODE_GIT_IPC_HANDLE: '/var/folders/k3/jljp0nzx523b73jhk6cldtqr0000gn/T/vscode-git-3d3b11e955.sock',
       npm_config_proxy: '',
       npm_config_package_lock: 'true',
       npm_config_package_lock_only: '',
       npm_config_save_optional: '',
       npm_config_user_agent: 'npm/6.11.3 node/v8.10.0 darwin x64',
       npm_config_ignore_scripts: '',
       port: '8000',
       VSCODE_GIT_ASKPASS_NODE: '/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)',
       GIT_ASKPASS: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh',
       npm_config_cache_lock_wait: '10000',
       npm_config_production: '',
       npm_package_dependencies_express: '~4.15.2',
       npm_config_save_bundle: '',
       npm_config_send_metrics: '',
       npm_config_init_version: '1.0.0',
       npm_config_node_options: '',
       npm_config_umask: '0022',
       npm_config_scope: '',
       npm_config_git: 'git',
       npm_config_init_author_name: '',
       npm_package_devDependencies_nodemon: '^2.0.3',
       npm_config_onload_script: '',
       npm_config_tmp: '/var/folders/k3/jljp0nzx523b73jhk6cldtqr0000gn/T',
       npm_config_unsafe_perm: 'true',
       COLORTERM: 'truecolor',
       npm_config_link: '',
       npm_config_prefix: '/usr/local',
       npm_node_execpath: '/usr/local/bin/node' },
    pid: 72872,
    features: 
     { debug: false,
       uv: true,
       ipv6: true,
       tls_npn: true,
       tls_alpn: true,
       tls_sni: true,
       tls_ocsp: true,
       tls: true },
    ppid: 72870,
    execPath: '/usr/local/bin/node',
    debugPort: 9229,
    _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
    _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
    _getActiveRequests: [Function: _getActiveRequests],
    _getActiveHandles: [Function: _getActiveHandles],
    reallyExit: [Function: reallyExit],
    abort: [Function: abort],
    chdir: [Function: chdir],
    cwd: [Function: cwd],
    umask: [Function: umask],
    getuid: [Function: getuid],
    geteuid: [Function: geteuid],
    setuid: [Function: setuid],
    seteuid: [Function: seteuid],
    setgid: [Function: setgid],
    setegid: [Function: setegid],
    getgid: [Function: getgid],
    getegid: [Function: getegid],
    getgroups: [Function: getgroups],
    setgroups: [Function: setgroups],
    initgroups: [Function: initgroups],
    _kill: [Function: _kill],
    _debugProcess: [Function: _debugProcess],
    _debugPause: [Function: _debugPause],
    _debugEnd: [Function: _debugEnd],
    hrtime: [Function: hrtime],
    cpuUsage: [Function: cpuUsage],
    dlopen: [Function: dlopen],
    uptime: [Function: uptime],
    memoryUsage: [Function: memoryUsage],
    binding: [Function: binding],
    _linkedBinding: [Function: _linkedBinding],
    _setupDomainUse: [Function: _setupDomainUse],
    _events: 
     { newListener: [Function],
       removeListener: [Function],
       warning: [Function],
       SIGWINCH: [ [Function], [Function] ] },
    _rawDebug: [Function],
    _eventsCount: 4,
    domain: null,
    _maxListeners: undefined,
    _fatalException: [Function],
    _exiting: false,
    assert: [Function],
    config: 
     { target_defaults: 
        { cflags: [],
          default_configuration: 'Release',
          defines: [],
          include_dirs: [],
          libraries: [] },
       variables: 
        { asan: 0,
          coverage: false,
          debug_devtools: 'node',
          debug_http2: false,
          debug_nghttp2: false,
          force_dynamic_crt: 0,
          host_arch: 'x64',
          icu_data_file: 'icudt60l.dat',
          icu_data_in: '../../deps/icu-small/source/data/in/icudt60l.dat',
          icu_endianness: 'l',
          icu_gyp_path: 'tools/icu/icu-generic.gyp',
          icu_locales: 'en,root',
          icu_path: 'deps/icu-small',
          icu_small: true,
          icu_ver_major: '60',
          llvm_version: 0,
          node_byteorder: 'little',
          node_enable_d8: false,
          node_enable_v8_vtunejit: false,
          node_install_npm: true,
          node_module_version: 57,
          node_no_browser_globals: false,
          node_prefix: '/',
          node_release_urlbase: 'https://nodejs.org/download/release/',
          node_shared: false,
          node_shared_cares: false,
          node_shared_http_parser: false,
          node_shared_libuv: false,
          node_shared_nghttp2: false,
          node_shared_openssl: false,
          node_shared_zlib: false,
          node_tag: '',
          node_use_bundled_v8: true,
          node_use_dtrace: true,
          node_use_etw: false,
          node_use_lttng: false,
          node_use_openssl: true,
          node_use_perfctr: false,
          node_use_v8_platform: true,
          node_without_node_options: false,
          openssl_fips: '',
          openssl_no_asm: 0,
          shlib_suffix: '57.dylib',
          target_arch: 'x64',
          uv_parent_path: '/deps/uv/',
          uv_use_dtrace: true,
          v8_enable_gdbjit: 0,
          v8_enable_i18n_support: 1,
          v8_enable_inspector: 1,
          v8_no_strict_aliasing: 1,
          v8_optimized_debug: 0,
          v8_promise_internal_field_count: 1,
          v8_random_seed: 0,
          v8_trace_maps: 0,
          v8_use_snapshot: true,
          want_separate_host_toolset: 0,
          xcode_version: '7.0' } },
    emitWarning: [Function],
    nextTick: [Function: nextTick],
    _tickCallback: [Function: _tickCallback],
    _tickDomainCallback: [Function: _tickDomainCallback],
    stdout: [Getter],
    stderr: [Getter],
    stdin: [Getter],
    openStdin: [Function],
    exit: [Function],
    kill: [Function],
    _immediateCallback: [Function: processImmediate],
    argv0: 'node',
    mainModule: 
     Module {
       id: '.',
       exports: {},
       parent: null,
       filename: '/Users/liqiankun/VSCodeProject/nodelearn/blog_express/bin/www',
       loaded: false,
       children: [ [Object], [Object] ],
       paths:  [ 
           '/Users/liqiankun/VSCodeProject/nodelearn/blog_express/bin/node_modules',
          '/Users/liqiankun/VSCodeProject/nodelearn/blog_express/node_modules',
          '/Users/liqiankun/VSCodeProject/nodelearn/node_modules',
          '/Users/liqiankun/VSCodeProject/node_modules',
          '/Users/liqiankun/node_modules',
          '/Users/node_modules',
          '/node_modules' ] } } 